Update refresh.yml
RafalMichalakBP/jira-automation pull request #27
Opened 2024-04-30 10:34 UTC by RafalMichalakBP

2024-04-30 10:34 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit fcb3cb13b57140983bb9a7cf6cd9ccd1ee21e099 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details>

2024-05-06 09:20 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 774495f618d009eca635a2c952b0be07def40a1c </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.02s =============================== 
```

</details>

2024-05-06 09:23 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit e07509ec62095d90eb85f0622db09a767da69186 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details>

2024-05-07 08:40 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 3a9450414b9fa6b30b9b3ab660e62cd1b0b9714d </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details>

2024-05-07 09:17 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit d4db077ec629fb03d9982294e40339eff4d3f85d </summary>

```python
  
```

</details>

2024-05-15 08:18 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results</summary>

```python
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s ===============================
```

</details>

2024-05-15 08:18 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results</summary>

```python
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s ===============================
```

</details>

:warning:

2024-05-15 08:24 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 5999dd3c46b21842d47e2d813b43065c54098b81 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.02s =============================== 
```

</details>

2024-05-15 08:30 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results</summary>

```python
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s ===============================
```

</details>

:warning:

2024-05-15 08:31 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results</summary>

```python
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.4.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s ===============================
```

</details>

:warning:

2024-05-15 08:32 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit e3a75318b2bb6929b92cfdc140f4fb1e7814793f </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details> 

 \:warning\:

2024-05-15 08:42 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 5a3c362f24f225bcd39b0d027d3132261b40d9da </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details> 

 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 08:50 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit b109570da8ca5df07e09b6095c8df7b91ac01319 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 1 item

test_sample.py::test_answer PASSED

============================== 1 passed in 0.01s =============================== 
```

</details> 

 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 08:59 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 2ab2a0ded3a6a90f5801efabbacc07747381cd63 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 ========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 

 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 09:00 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 2ab2a0ded3a6a90f5801efabbacc07747381cd63 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 

 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 09:01 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit bee0882d29a0921ef004f1e7f44f17cbf3da5128 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 

 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 09:12 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= ```

2024-05-15 09:12 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:13 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> n \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: ```python


\r
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:13 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: ```python


 
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:14 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python


  =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:14 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 
 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python


  =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:15 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 
 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
  =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:15 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 430e30b4940c83c13f6a06a4a70e937350e73c6b </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 
 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 

```python
  =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:17 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 3ae103d818d86907e646215f448e017d987a1374 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= ```

2024-05-15 09:20 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit cd6d5131b0882fc82f840a54b360d9ad509e4c8e </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= ```

2024-05-15 09:28 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 606eaa8ac0cb543b2093118d1ac50cea5b445677 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 ============================= test session starts ============================== platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3 cachedir: .pytest_cache rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation collecting ... collected 2 items test_sample.py::test_one PASSED test_sample.py::test_answer PASSED =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:37 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 7b69336f2f600ce44c5906890b9010d6d07a4559 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details> ```python


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.02s ========================= 
```

2024-05-15 09:37 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 7b69336f2f600ce44c5906890b9010d6d07a4559 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details> 


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: ```python
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.02s ========================= 
```

2024-05-15 09:38 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 7b69336f2f600ce44c5906890b9010d6d07a4559 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details> 


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
 ```python
 =============================== warnings summary =============================== test_sample.py::test_one /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2 warnings.warn(UserWarning('api v1, should use functions from v2')) -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================= 2 passed, 1 warning in 0.02s ========================= 
```

2024-05-15 09:39 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view test results for commit 64e6b86e0a5a009f6cf8fa605c36b487ac0eb6e0 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details> 


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

2024-05-15 09:44 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit c1c3912a7492a79a2cf289094f0a30ad62d381cd </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 


 \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

2024-05-15 09:47 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 7b68c9acb323936fb492efc4fc1f6d0a2158e9b0 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details> 


 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

2024-05-15 09:52 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit d679fe247617c64c0e960825550c0656b9ffb200 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 


 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```

2024-05-15 09:54 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 3235519920f2e3630afbaf31ba47cf6bc39f738f </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 


 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 09:57 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 2a8b71b7f77bc7ec24844b3b1a47e65e3f0f9641 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 


 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 10:00 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 4ec693f923e24c9c7964553ddae04b95b12fdac1 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

============================== 2 passed in 0.01s =============================== 
```

</details>

2024-05-15 10:02 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 19875cf119527ccfa6e7ba3b5218791b93929df5 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details> 


 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 10:18 UTC, RafalMichalakBP commented on .github/workflows/refresh.yml
> -          ref: ${{ github.head_ref || github.ref_name }}
cokolwiek

2024-05-15 10:31 UTC, RafMic requested changes
Review warnings before merging

2024-05-15 10:50 UTC, RafMic requested changes
PLEASE REVIEW WARNINGS BEFORE MERGING

2024-05-15 10:57 UTC, RafMic approved these changes

2024-05-15 11:13 UTC, RafMic requested changes
PLEASE REVIEW WARNINGS BEFORE MERGING

2024-05-15 11:14 UTC, RafMic approved these changes

2024-05-15 11:17 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit cebd416110092a9bd82767ed152b2ce0df869921 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details>

2024-05-15 11:24 UTC, RafMic requested changes
# \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
``` 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 11:24 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 3d0da5d5e745747542919ced7c0849955b9a4f42 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details>

2024-05-15 11:27 UTC, RafalMichalakBP commented
<details>
<summary>Expand to view full test results for commit 0179a8458860fb93c4bbce785a8c2762bd0b04ed </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details>

2024-05-15 11:27 UTC, RafMic requested changes
# \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 # \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

2024-05-15 11:28 UTC, closed without merging